SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ACTIVITE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LIBELLE] [nvarchar](max) NULL,
	[JOURTRAVAILLE] [datetime] NOT NULL,
	[NBHEURES] [real] NOT NULL,
	[TAUX] [real] NOT NULL,
	[CREATEDBY] [nvarchar](max) NULL,
	[DTCREATION] [datetime] NULL,
	[MODIFIEDBY] [nvarchar](max) NULL,
	[DTMODIF] [datetime] NULL,
	[FK_CRAID] [int] NOT NULL,
	[FK_IDTYPEACTIVITE] [bigint] NOT NULL,
	[AddedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.ACTIVITE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ACTIVITE]  WITH CHECK ADD  CONSTRAINT [FK_ACTIVITE_CRA_ID] FOREIGN KEY([FK_CRAID])
REFERENCES [dbo].[CRA] ([CRAID])
GO