//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRA_Activite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRA_Activite()
        {
            this.CRA_ActiviteDetail = new HashSet<CRA_ActiviteDetail>();
            this.CRA_ActiviteStates = new HashSet<CRA_ActiviteStates>();
            this.LNK_Users_CRAActivite = new HashSet<LNK_Users_CRAActivite>();
        }
    
        public int Id { get; set; }
        public int UsersId { get; set; }
        public int CRATypeId { get; set; }
        public string Period { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModificaitonDate { get; set; }
        public string ModificaitonBy { get; set; }
        public Nullable<System.DateTime> PeriodBegin { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
    
        public virtual CRA_Type CRA_Type { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRA_ActiviteDetail> CRA_ActiviteDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRA_ActiviteStates> CRA_ActiviteStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNK_Users_CRAActivite> LNK_Users_CRAActivite { get; set; }
    }
}
