//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_SendListe
    {
        public int Id { get; set; }
        public int UsersId { get; set; }
        public int EmailTypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateSended { get; set; }
        public Nullable<System.DateTime> DateReceipted { get; set; }
        public Nullable<System.DateTime> DateReaded { get; set; }
        public string SubjectBuilded { get; set; }
        public string BodyBuilded { get; set; }
    
        public virtual Email_Type Email_Type { get; set; }
        public virtual Users Users { get; set; }
    }
}
