//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCSolutions.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCEntities : DbContext
    {
        public MCEntities()
            : base("name=MCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Company_Adresse> Company_Adresse { get; set; }
        public virtual DbSet<CRA_Activite> CRA_Activite { get; set; }
        public virtual DbSet<CRA_ActiviteDetail> CRA_ActiviteDetail { get; set; }
        public virtual DbSet<CRA_ActiviteState> CRA_ActiviteState { get; set; }
        public virtual DbSet<CRA_ActiviteStates> CRA_ActiviteStates { get; set; }
        public virtual DbSet<CRA_Definition> CRA_Definition { get; set; }
        public virtual DbSet<CRA_LibeleCol> CRA_LibeleCol { get; set; }
        public virtual DbSet<CRA_Type> CRA_Type { get; set; }
        public virtual DbSet<Email_SendListe> Email_SendListe { get; set; }
        public virtual DbSet<Email_Type> Email_Type { get; set; }
        public virtual DbSet<Email_Variables> Email_Variables { get; set; }
        public virtual DbSet<Invitation_Queued> Invitation_Queued { get; set; }
        public virtual DbSet<Invitation_State> Invitation_State { get; set; }
        public virtual DbSet<Invitation_Type> Invitation_Type { get; set; }
        public virtual DbSet<LNK_Users_CRAActivite> LNK_Users_CRAActivite { get; set; }
        public virtual DbSet<LNK_Users_CRAType> LNK_Users_CRAType { get; set; }
        public virtual DbSet<LNK_Users_Mission> LNK_Users_Mission { get; set; }
        public virtual DbSet<LNK_Users_UserRole> LNK_Users_UserRole { get; set; }
        public virtual DbSet<Mission> Mission { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Adresse> Users_Adresse { get; set; }
        public virtual DbSet<Users_Email> Users_Email { get; set; }
        public virtual DbSet<Users_Password> Users_Password { get; set; }
        public virtual DbSet<Users_Roles> Users_Roles { get; set; }
        public virtual DbSet<Users_Tel> Users_Tel { get; set; }
    }
}
